[2023-07-11T02:07:52.162+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_users.create_table scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T02:07:52.170+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_users.create_table scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2023-07-11T02:07:52.170+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T02:07:52.181+0000] {taskinstance.py:1327} INFO - Executing <Task(SQLExecuteQueryOperator): create_table> on 2023-07-10 00:00:00+00:00
[2023-07-11T02:07:52.191+0000] {standard_task_runner.py:57} INFO - Started process 1834 to run task
[2023-07-11T02:07:52.199+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_users', 'create_table', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmpifl8p84v']
[2023-07-11T02:07:52.203+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask create_table
[2023-07-11T02:07:52.287+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_users.create_table scheduled__2023-07-10T00:00:00+00:00 [running]> on host 5f08e8e1aa21
[2023-07-11T02:07:52.393+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Trubiano' AIRFLOW_CTX_DAG_ID='etl_users' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2023-07-11T02:07:52.394+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE IF NOT EXISTS users (
    name VARCHAR(70),
    gender VARCHAR(1),
    age INT,
    is_under_20 BOOLEAN,
    is_over_40 BOOLEAN,
    email VARCHAR(50),
    nationality VARCHAR(5),
    process_date VARCHAR(10) distkey
) SORTKEY(process_date, nationality);
[2023-07-11T02:07:52.407+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2023-07-11T02:07:52.892+0000] {base.py:73} INFO - Using connection ID 'redshift_default' for task execution.
[2023-07-11T02:07:54.649+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 171, in get_conn
    return redshift_connector.connect(**conn_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/__init__.py", line 364, in connect
    numeric_to_float=info.numeric_to_float,
  File "/home/airflow/.local/lib/python3.7/site-packages/redshift_connector/core.py", line 721, in __init__
    raise self.error
redshift_connector.error.InterfaceError: {'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user "postgres"', 'F': '../src/pg/src/backend/libpq/auth.c', 'L': '418', 'R': 'auth_failed'}
[2023-07-11T02:07:54.711+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=etl_users, task_id=create_table, execution_date=20230710T000000, start_date=20230711T020752, end_date=20230711T020754
[2023-07-11T02:07:54.745+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task create_table ({'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user "postgres"', 'F': '../src/pg/src/backend/libpq/auth.c', 'L': '418', 'R': 'auth_failed'}; 1834)
[2023-07-11T02:07:54.791+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T02:07:54.850+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
